markdown: rdiscount
safe: true
lsi: false
pygments: true
permalink: /posts/:title
title : Kebre
production_url : http://dev.kebre.net
description: "Thougths, tutorials and hacks by Kev."
disqus_shortname: kebrenet
# analytics: UA-32899481-1
gauges: 50f1f940613f5d2cfe000026
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
author :
  name : Kevin
  github : kebre001
  twitter : kebre001
  facebook : kebre
  email: kebre001[at]gmail.com
