markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : Kebre
production_url : http://carlosbecker.com
description: "Througths, flamewars, utilities, tutorials, codes, projects and other things by Carlos Alexandro Becker."
disqus_shortname: kebrenet
analytics: UA-32899481-1
gauges: 50f2b533613f5d7c8000000c
author :
  name : Kev
  github : kebre001
  twitter : kebre001
  email: none@gmail.com
